### ISSUE TITLE
Mining mineral sound effect not consistently played

### ISSUE THREAD

**Issue by hdieset** [Mathieu96/fatherload#2]
Holding down a directional button, and mining a mineral does not always cause the *pling* noise to be played.

**Comment by Mathieu96** [comment]
It may come from the fact that the sound effect of the truck moving is playing at the same time and 2 sound effects can't play at the same time?

**Comment by hdieset** [comment]
Now, only one audio clip is played when the vehicle is drilling. If this is not enough, then maybe the background audio needs to be paused while playing sound effects?

**Comment by Mathieu96** [comment]
No sound effects can be played at the same time as the background music, your solution seems to fix this issue.
