### ISSUE TITLE
Minerals initiated on top of each other

### ISSUE THREAD

**Issue by hdieset** [Mathieu96/fatherload#3]
The initialization process does not take into account that other minerals might already be placed in the randomly selected coordinates - a check needs to be made.

**Comment by Mathieu96** [comment]
It may be a bit heavy to check it, I noticed that when we start the game it's already slow to launch everything, the cores aren't very fast

**Comment by hdieset** [comment]
Fixed.

**Comment by Mathieu96** [comment]
Since this update, the restarting is an issue, the random generation goes crazy.

**Comment by Mathieu96** [comment]
Fixed. It came from the fuel not initialized in the good function.
