### ISSUE TITLE
Lack of gravity

### ISSUE THREAD

**Issue by hdieset** [Mathieu96/fatherload#4]
The vehicle can fly/levitate in the air below ground. This could be solved by having a variable `isFlying` and then add a default condition to the switch case in `switch(keys)` that is almost the same as down movement, but it won't naturally use the drill.

**Comment by Mathieu96** [comment]
For now, it is more a minimalist game, the gravity is a bit tricky to introduce so it is a way to improve later. Furthermore, it means that we need a new picture for the character.

**Comment by Mathieu96** [comment]
Done, now the player falls if there is nothing below it, the player can also fly over the ground. (The UP move costs more fuel than the other, like when drilling: 2).
