### ISSUE TITLE
Pause menu text

### ISSUE THREAD

**Issue by hdieset** [Mathieu96/fatherload#6]
If we have the time - the text displayed in the pause menu isn't intuitive IMO. When the game is paused, it shows "START", but I personally think it would be better if it displayed "PAUSED".

**Comment by Mathieu96** [comment]
Yeah seems right, the problem is that it is quite long to draw it, we can change it later.

**Comment by Mathieu96** [comment]
Fixed. Now, it displays "PAUSE".
